---
- name: '[dependencies] Install ohmyzsh dependencies for non-Darwin systems: zsh, git'
  package:
    name: [ 'zsh', 'git', 'bc' ]
    state: latest
  when: ansible_os_family != 'Darwin'
  become: yes  # disable this for MacOS
  tags:
    - ohmyzsh
    - ohmyzsh_dependencies

- name: '[dependencies] Make sure locales package is installed on Debian'
  apt: name=locales state=present
  when: ansible_os_family == 'Debian'

# MacOS:
- name: '[dependencies] Install powerlevel9k dependencies: bc'
  homebrew: name=bc state=latest
  when:
    - ohmyzsh_powerlevel9k == true
    - ansible_os_family == 'Darwin'
  become: no    # always the case with homebrew
  tags:
    - ohmyzsh
    - ohmyzsh_dependencies

- name: '[dependencies] Install zsh for MacOS; install_options: --with-unicode9, --without-etcdir'
  homebrew:
    install_options:
      - 'with-unicode9'
      - 'without-etcdir'
    name: zsh
    state: latest
    update_homebrew: yes
  when: ansible_os_family == 'Darwin'
  become: no
  tags:
    - ohmyzsh
    - ohmyzsh_dependencies
...
