---
- name: '[install] Include {{ ansible_os_family }}-specific variables'
  include_vars: "{{ ansible_os_family }}.yml"
  tags: ohmyzsh

- name: '[install] Clone oh-my-zsh repo'
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh.git
    dest: "{{ ohmyzsh_install_dir }}"
    version: master
    update: yes
  become: yes
  tags: ohmyzsh

- name: '[install] Clone Powerlevel9k theme to custom directory'
  git:
    repo: https://github.com/bhilburn/powerlevel9k.git
    dest: "{{ ohmyzsh_install_dir }}/custom/powerlevel9k"
    version: master
    update: yes
  become: yes
  when: ohmyzsh_powerlevel9k is defined and true
  tags: ohmyzsh

- name: '[install] Setup zprofile for zsh'
  template:
    src: zprofile.j2
    dest: "{{ ohmyzsh_zprofile_dir }}/zprofile"
    mode: 0644
    owner: root
    group: root
  become: yes
  when: ansible_os_family != 'Darwin'
  tags: ohmyzsh

# For Debian and maybe other distros:
- name: '[install] Set up en_US.UTF-8 locale'
  locale_gen:
    name: en_US.UTF-8
    state: present
  when:
  - ansible_os_family != 'Darwin'
  - ansible_os_family != 'RedHat'
  become: yes
  tags: ohmyzsh
...
